name: Daily Auto Deploy

on:
  schedule:
    # Runs every day at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Trigger Cloudflare Pages Deploy
    
    steps:
      - name: Trigger Deploy Hook
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/d393a373-67de-49b9-a2b4-aa70635aa90c"
          echo "Deploy hook triggered successfully at $(date)"
      
      - name: Notify Success
        run: |
          echo "✅ Daily deployment triggered for ArtCasa website"
          echo "Timestamp: $(date)"
          echo "Deploy hook URL called successfully"
